//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSimulation.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MobileApplication()
        {
            this.AndroidDeviceTokens = new HashSet<AndroidDeviceToken>();
            this.IosDeviceTokens = new HashSet<IosDeviceToken>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Certificate { get; set; }
        public string LinkName { get; set; }
        public int SiteID { get; set; }
        public byte Platform { get; set; }
        public byte IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AndroidDeviceToken> AndroidDeviceTokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IosDeviceToken> IosDeviceTokens { get; set; }
    }
}
