//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSimulation.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PHO_PARTEntities : DbContext
    {
        public PHO_PARTEntities()
            : base("name=PHO_PARTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AndroidDeviceToken> AndroidDeviceTokens { get; set; }
        public virtual DbSet<IosDeviceToken> IosDeviceTokens { get; set; }
        public virtual DbSet<MobileApplication> MobileApplications { get; set; }
    }
}
