//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSimulation.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNotificationContent
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string IosModel { get; set; }
        public string AndroidModel { get; set; }
    }
}
