//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSimulation.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tResponse()
        {
            this.tResponseDetails = new HashSet<tResponseDetail>();
        }
    
        public int ID { get; set; }
        public string Url { get; set; }
        public string Category { get; set; }
        public System.DateTime CreateDate { get; set; }
        public short Hit { get; set; }
        public System.DateTime LastRequestDate { get; set; }
        public bool IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tResponseDetail> tResponseDetails { get; set; }
    }
}
