//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSimulation.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tResponseDetail
    {
        public int ID { get; set; }
        public int ResponseID { get; set; }
        public string ContentType { get; set; }
        public string ContentRaw { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Delay { get; set; }
        public short Hit { get; set; }
        public bool UseTemplateEngine { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual tResponse tResponse { get; set; }
    }
}
